<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.74.0.4162" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
  </ItemGroup>

</Project>
