import type { JobResult } from "./types";

export const jobResults: JobResult[] = [
  {
    id: "reed-senior-fullstack-engineer-001",
    source: "Reed",
    title: "Senior Fullstack Engineer",
    company: "FinTech Platform",
    location: "Milton Keynes",
    distanceMiles: 6.4,
    employmentType: "Permanent",
    workMode: "Hybrid",
    salaryMinGbp: 80000,
    salaryMaxGbp: 95000,
    postedDate: "2026-05-30",
    score: 92,
    recommended: true,
    reasons: ["Strong .NET and React alignment", "Salary above target", "Hybrid within preferred radius"],
    risks: ["Financial services domain may require regulatory experience"],
    url: "https://www.reed.co.uk/jobs/senior-fullstack-engineer-jobs",
  },
  {
    id: "jobserve-lead-developer-002",
    source: "JobServe",
    title: "Lead Developer",
    company: "Cloud Delivery Consultancy",
    location: "Remote UK",
    distanceMiles: 0,
    employmentType: "Contract",
    workMode: "Remote",
    dayRateMinGbp: 525,
    dayRateMaxGbp: 600,
    contractMonths: 6,
    postedDate: "2026-05-29",
    score: 88,
    recommended: true,
    reasons: ["Day rate clears target", "Remote role", "Leadership and delivery fit"],
    risks: ["Contract extension not guaranteed"],
    url: "https://www.jobserve.com/gb/en/Job-Search/",
  },
  {
    id: "reed-senior-software-developer-003",
    source: "Reed",
    title: "Senior Software Developer",
    company: "HealthTech Product Team",
    location: "Oxford",
    distanceMiles: 39.8,
    employmentType: "Permanent",
    workMode: "Office",
    salaryMinGbp: 75000,
    salaryMaxGbp: 85000,
    postedDate: "2026-05-28",
    score: 76,
    recommended: false,
    reasons: ["Matches senior .NET profile", "Salary meets minimum threshold"],
    risks: ["Office-first role", "Longer commute than preferred"],
    url: "https://www.reed.co.uk/jobs/senior-software-developer-jobs",
  },
  {
    id: "jobserve-senior-dotnet-engineer-004",
    source: "JobServe",
    title: "Senior .NET Engineer",
    company: "Payments Scaleup",
    location: "London",
    distanceMiles: 49.5,
    employmentType: "Contract",
    workMode: "Hybrid",
    dayRateMinGbp: 650,
    dayRateMaxGbp: 700,
    contractMonths: 12,
    postedDate: "2026-05-27",
    score: 84,
    recommended: true,
    reasons: ["Strong C# and distributed systems fit", "Excellent contract rate", "Long contract duration"],
    risks: ["London hybrid pattern may add travel cost"],
    url: "",
  },
  {
    id: "reed-platform-engineer-005",
    source: "Reed",
    title: "Senior Platform Engineer",
    company: "Retail Technology Group",
    location: "Northampton",
    distanceMiles: 18.2,
    employmentType: "Permanent",
    workMode: "Hybrid",
    salaryMinGbp: 78000,
    salaryMaxGbp: 88000,
    postedDate: "2026-05-27",
    score: 81,
    recommended: true,
    reasons: ["Good cloud and backend alignment", "Within commute radius", "Salary above threshold"],
    risks: ["Less frontend React ownership than ideal"],
    url: "",
  },
  {
    id: "reed-react-dotnet-fullstack-006",
    source: "Reed",
    title: "Senior React .NET Fullstack Developer",
    company: "SaaS Operations Platform",
    location: "Remote UK",
    distanceMiles: 0,
    employmentType: "Permanent",
    workMode: "Remote",
    salaryMinGbp: 90000,
    salaryMaxGbp: 105000,
    postedDate: "2026-05-26",
    score: 95,
    recommended: true,
    reasons: ["Excellent React and .NET match", "Remote role", "Highest salary band in current list"],
    risks: ["May expect product-led SaaS background"],
    url: "",
  },
  {
    id: "jobserve-azure-lead-007",
    source: "JobServe",
    title: "Azure Lead Developer",
    company: "Public Sector Delivery Partner",
    location: "Birmingham",
    distanceMiles: 48.1,
    employmentType: "Contract",
    workMode: "Office",
    dayRateMinGbp: 450,
    dayRateMaxGbp: 500,
    contractMonths: 6,
    postedDate: "2026-05-25",
    score: 70,
    recommended: false,
    reasons: ["Rate and duration meet minimums", "Leadership responsibilities match profile"],
    risks: ["Office pattern is weak fit", "Public sector clearance may be required"],
    url: "",
  },
  {
    id: "reed-engineering-manager-008",
    source: "Reed",
    title: "Hands-on Engineering Manager",
    company: "Logistics Product Company",
    location: "Bedford",
    distanceMiles: 17.6,
    employmentType: "Permanent",
    workMode: "Hybrid",
    salaryMinGbp: 85000,
    salaryMaxGbp: 100000,
    postedDate: "2026-05-24",
    score: 79,
    recommended: false,
    reasons: ["Compensation and commute fit", "Technical leadership overlap"],
    risks: ["May reduce hands-on fullstack engineering time"],
    url: "",
  },
  {
    id: "jobserve-fullstack-contract-009",
    source: "JobServe",
    title: "Fullstack Developer",
    company: "InsurTech Programme",
    location: "Milton Keynes",
    distanceMiles: 4.7,
    employmentType: "Contract",
    workMode: "Hybrid",
    dayRateMinGbp: 400,
    dayRateMaxGbp: 475,
    contractMonths: 6,
    postedDate: "2026-05-23",
    score: 73,
    recommended: false,
    reasons: ["Local contract role", "Minimum rate and duration are met"],
    risks: ["Title is not explicitly senior", "Rate is at the lower threshold"],
    url: "",
  },
  {
    id: "reed-principal-software-engineer-010",
    source: "Reed",
    title: "Principal Software Engineer",
    company: "Data Products Studio",
    location: "Cambridge",
    distanceMiles: 47.9,
    employmentType: "Permanent",
    workMode: "Remote",
    salaryMinGbp: 95000,
    salaryMaxGbp: 115000,
    postedDate: "2026-05-22",
    score: 89,
    recommended: true,
    reasons: ["Senior technical scope", "Remote-first", "Strong compensation"],
    risks: ["Principal title may require architecture interview depth"],
    url: "",
  },
];
